#!/usr/bin/perl -w
# nagios: -epn
#
# Perl Nagios check plugin for Areca RAID
#
# Created to work on a DDP-16D storage appliance running a very
# old version of Debian and Areca CLI 1.13.0
#
# Copyright 2015 Joshua Malone <jmalone@nrao.edu>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

# These lines include the Nagios-provided exit code perl module.
# You may need to adjust the location of your included lib directory.
use lib qw ( . /usr/lib/nagios/libexec /usr/lib/nagios/plugins );
use utils qw(%ERRORS);

# Uncomment this line to use the Net::SNMP library
#use Net::SNMP;
use Getopt::Long qw(:config no_ignore_case);

# Set the name of your plugin script here. This will be used
# in the help and version output.
$PROGNAME="check_areca";

# Enter the version number of your plugin here. Remember to
# increment this version each time your release or commit it.
# You can use integers or real numbers (x.y) as you please.
$VERSION=2;

# Your name - used in version output
$AUTHOR_NAME='Josh Malone';

# Your email address or other info string. Be sure to use
# single-quotes so that perl doesn't interpret an email address
# as an array.
$AUTHOR_INFO='jmalone@nrao.edu';

# Help function.
# This function is called to provide usage information to the user
# either when asked for via --help or -h or when an illegal option
# is given on the command line. Be sure to add any additional options
# that you use in your plugin to this output.
sub print_help () {
    my $help = << "EOH";
Usage: $PROGNAME [options]

    -C, --cli-path	Full path to the Areca cli
    --check-disks	Perform deep check of disk status (longer run-time)
    -v, --verbose	Print verbose debugging output
    -V, --version	Print the plugin version and exit
    -h, --help		Print this help text

EOH
    print ($help);
    exit $ERRORS{'UNKNOWN'};
}

### Set some defaults
#
# Default status is 'OK'. Change the status if any threshold is exceeded.
# Note: This logic may or may not work for your plugin. Change this line
# if your plugin logic works differently.
$status='OK';

# You can also define some default thresholds if there are logical defaults
# for you application (disk usage at 90%, room temperature above 75F, etc.)
# These will be overridden by values on the command line (parsed below).
#
# $warn = '80';
# $crit = '90';
$clipath='/usr/local/bin/cli32';

# Series label for performance data output. Should reflect what is being
# measured in the perfdata as it will be shown in the graphs
$perfLabel='label';
$perfUnit='suffix';

GetOptions(
    "C|cli-path"	=> \$clipath,
    "check-disks"	=> \$checkDisks,
    "w|warning=s"	=> \$warn,
    "c|critical=s"	=> \$crit,
    "v|verbose"		=> \$debug,
    "V|version"		=> \$doVersion,
    "h|help"		=> \$helpMe,
) or print_help();

if ($doVersion) {
    printf("%s by %s (%s) version %d\n", $PROGNAME, $AUTHOR_NAME, $AUTHOR_INFO, $VERSION);
    exit $ERRORS{'UNKNOWN'};
}
if ($helpMe) {
    # This call exits automatically.
    print_help();
}

### Parse threshold ranges in Nagios range syntax.
# https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
#
# Currently, this template only supports "outside the range" syntax
# and does not support the use of ~ for infinity. To-do!
@Warn=split(':', $warn) if (defined($warn));
@Crit=split(':', $crit) if (defined($crit));
if(scalar(@Warn) > 1) {
    printf("Checking low and high warning thresholds\n") if ($debug);
    ($warnLow, $warn)=@Warn;
}
if(scalar(@Crit) > 1) {
    printf("Checking low and high critical thresholds\n") if ($debug);
    ($critLow, $crit)=@Crit;
}
if(defined ($warn) && $debug) {
    printf("Thresholds in use: W->%d:%d , C->%d:%d\n", $warnLow, $warn, $critLow, $crit);
}

##########  Write your plugin logic below this line  #############

=pod

Your plugin should now do it's work to perfom some check and compare
the state of some service or metric to the warning and critical
thresholds. If your check does not use numeric thresholds, then the
$warn and $crit values can jus be ignored in the template.

Your check logic should set the following variables:

  $status = The textual status of the service (OK, WARNING, etc.)
  $info = Additional info about the state of the service - used
          in the Screen output

You *MUST* place your code outside the =pod and =cut lines so that
Perl actually runs the code for your service check.

=cut

$status="OK";
$info="";

# Set alarm to time out possibly hung Areca cli command
# alarm 40;
$SIG{ALRM} = sub {
    print "UNKNOWN: Plugin timed out - possibly a hung Areca cli command\n";
    exit $ERRORS{'UNKNOWN'};
};

# Check RAID sets
open (RSF, "$clipath rsf info |") or die ("Can't open areca CLI");
while ($rsfline=<RSF>) {
    if ($rsfline=~m/^ \d/) {
    	# RAID set line
	my @rsfstat=split(/\s+/, $rsfline);
	printf(" Detected Raid set %s (%d disks)\n", $rsfstat[2], $rsfstat[3] ) if ($debug);
	if( lc $rsfstat[7] ne "normal") {
	    $status="CRITICAL";
	    $info.=sprintf("RAID set %s is %s\n", $rsfstat[2], $rsfstat[7]);
	}
    }
}
close(RSF);
# Check Volume sets
open (VSF, "$clipath vsf info |") or die ("Can't open Areca CLI");
while ($vsfline=<VSF>) {
    if($vsfline=~m/^ *\d/) {
    	my @vsfstat=split(/\s+/, $vsfline);
	printf(" Detected volume %s (%s)\n", $vsfstat[2], $vsfstat[4]) if ($debug);
	$stat=lc($vsfstat[7]);
	if ($stat ne "normal") {
	    if ($stat eq "rebuilding" ) {
		$status="WARNING";
	    } elsif ($stat eq "verifying") {
	    	$status="OK";
	    } else {
	    	$status="CRITICAL";
	    }
	    $info.=sprintf("Volume %s is %s\n", $vsfstat[2], $vsfstat[7]);
	}
    }
}
close (VSF);

if(defined($checkDisks)) {
    # Check detailed disk data (optional as it makes check take longer)
    my %diskstat=();
    open (CLI, "$clipath disk info |") or die ("Can't open Areca CLI");
    while ($dline=<CLI>) {
	if ($dline=~m/ Disk\d/) {
	    @dinfo=split(/\s+/, $dline);
	    printf(" Detected disk %d (%s)\n", $dinfo[1], $dinfo[3]) if ($debug);
	    push(@disks, $dinfo[1]);
	}
    }
    close (CLI);
}

# The $perfValue variable can be set to some metric to be reported as
# performance data (perfdata). If your plugin has no metrics to be
# reported, leave $perfValue undefined
#
# $perfValue=42;
if (!$info) {
    $info="No problems detected by plugin";
}

#############  End of your plugin logic  ##############

# The Screen output should always begin with the readable status value
# ('OK', 'WARNING', 'CRITICAL' or 'UNKNOWN')
$outstring="$status: $info";

if(defined($perfValue)) {
    # Compile the performance data. If threshold ranges are in use, format
    # the thresholds in perfdata range format as well.
    if(defined($critLow)) {
	$perfWarnCrit=sprintf("%d:%d;%d:%d", $warnLow, $warn, $critLow, $crit);
    } else {
	$perfWarnCrit=sprintf("%d;%d", $warn, $crit);
    }
    $perfData=sprintf("|%s=%d%s;%s", $perfLabel, $perfValue, $perfUnit, $perfWarnCrit);
}

if(defined($perfValue)) {
    # Concatenate the Screen Ouput and perfdata to stdout so that Nagios can grab it.
    print "$outstring$perfData\n";
} else {
    print "$outstring\n";
}

# Exit with the status exit code appropriate to the textual status.
exit $ERRORS{$status};
