#!/usr/bin/perl -w
# nagios: -epn
#
# Nagios check for Atlassian Confluence groups
#
# This plugin will check aspects of a Confluence group
#
#
# Copyright 2021 Joshua Malone <jmalone@nrao.edu>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

# These lines include the Nagios-provided exit code perl module.
# You may need to adjust the location of your included lib directory.
use lib qw ( . /usr/lib64/nagios/plugins /usr/lib/nagios/plugins );
use utils qw(%ERRORS);
use LWP::UserAgent;
use HTTP::Request;
use JSON;
use MIME::Base64;
use strict;

# Uncomment this line to use the Net::SNMP library
#use Net::SNMP;
use Getopt::Long qw(:config no_ignore_case);

# Set the name of your plugin script here. This will be used
# in the help and version output.
my $PROGNAME="check_confluence_group";

# Enter the version number of your plugin here. Remember to
# increment this version each time your release or commit it.
# You can use integers or real numbers (x.y) as you please.
my $VERSION=2;

# Your name - used in version output
my $AUTHOR_NAME='Josh Malone';

# Your email address or other info string. Be sure to use
# single-quotes so that perl doesn't interpret an email address
# as an array.
my $AUTHOR_INFO='jmalone@nrao.edu';

# Help function.
# This function is called to provide usage information to the user
# either when asked for via --help or -h or when an illegal option
# is given on the command line. Be sure to add any additional options
# that you use in your plugin to this output.
sub print_help () {
    my $help = << "EOH";
Usage: $PROGNAME -H <host address> [args] [-vV]

Required args:
    -H, --host          Hostname of your cloud Confluence instance
                        (Usually \$HOSTADDRESS\$ in Nagios)
    -m, --mode          Check mode (see MODES)
    -U, --api-user      API username (user\@host usually)
    -P, --api-pass      API key for api-user
    -g, --group         Group to check
    -w, --warning       Warning threshold (supports Nagios range syntax)
    -c, --critical      Critical threshold (supports Nagios range syntax)

Optional args:
    -v, --verbose       Print verbose debugging output
    -V, --version       Print the plugin version and exit

MODES:
    size - Check that a group doesn't exceed <threshold> members

EOH
    print ($help);
    exit $ERRORS{'UNKNOWN'};
}

my $groupname;
my $mode;
my $warn;
my $crit;
my $warnLow;
my $critLow;
my $api_user;
my $api_pass;
my $hostaddress;
my $helpMe=undef;
my $debug=0;
my $doVersion=undef;
my $perfValue=undef;
my $perfData=undef;

### Set some defaults
#
# Default status is 'OK'. Change the status if any threshold is exceeded.
# Note: This logic may or may not work for your plugin. Change this line
# if your plugin logic works differently.
my $status='OK';
my $info='';

# You can also define some default thresholds if there are logical defaults
# for you application (disk usage at 90%, room temperature above 75F, etc.)
# These will be overridden by values on the command line (parsed below).
#
# $warn = '80';
# $crit = '90';

# Series label for performance data output. Should reflect what is being
# measured in the perfdata as it will be shown in the graphs
my $perfLabel='label';
my $perfUnit='';

GetOptions(
    "H|host=s"		=> \$hostaddress,
    "h|help"		=> \$helpMe,
    "g|group=s"     => \$groupname,
    "m|mode=s"      => \$mode,
    "U|api-user=s"  => \$api_user,
    "P|api-pass=s"  => \$api_pass,
    "w|warning=s"	=> \$warn,
    "c|critical=s"	=> \$crit,
    "v|verbose"		=> \$debug,
    "V|version"		=> \$doVersion,
) or print_help();

if ($doVersion) {
    printf("%s by %s (%s) version %d\n", $PROGNAME,
        $AUTHOR_NAME, $AUTHOR_INFO, $VERSION);
    exit $ERRORS{'UNKNOWN'};
}
if ($helpMe) {
    # This call exits automatically.
    print_help();
}

### Parse threshold ranges in Nagios range syntax.
# https://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT
#
# Currently, this template only supports "outside the range" syntax
# and does not support the use of ~ for infinity. To-do!
my @Warn=split(':', $warn) if (defined($warn));
my @Crit=split(':', $crit) if (defined($crit));
if(scalar(@Warn) > 1) {
    printf("Checking low and high warning thresholds\n") if ($debug);
    ($warnLow, $warn)=@Warn;
}
if(scalar(@Crit) > 1) {
    printf("Checking low and high critical thresholds\n") if ($debug);
    ($critLow, $crit)=@Crit;
}
printf("Thresholds in use: W->%d:%d , C->%d:%d\n", $warnLow, $warn, $critLow, $crit) if ($debug);

##########  Write your plugin logic below this line  #############

=pod

Your plugin should now do it's work to perfom some check and compare
the state of some service or metric to the warning and critical
thresholds. If your check does not use numeric thresholds, then the
$warn and $crit values can jus be ignored in the template.

Your check logic should set the following variables:

  $status = The textual status of the service (OK, WARNING, etc.)
  $info = Additional info about the state of the service - used
          in the Screen output

You *MUST* place your code outside the =pod and =cut lines so that
Perl actually runs the code for your service check.

=cut

my $apirest=sprintf("https://%s/wiki/rest/api/group/%s/member",
    $hostaddress, $groupname);
my $auth_header = encode_base64("$api_user:$api_pass");

my $headers = [
    'Content-Type'  => 'application/json',
    'Authorization' => "Basic $auth_header",
    'Accept'        => 'application/json',
];
my $req = HTTP::Request->new(
    'GET', $apirest, $headers);
my $ua = LWP::UserAgent->new();
$ua->agent($PROGNAME.'/'.$VERSION);
my $res = $ua->request($req);
my $content = decode_json( $res->{'_content'} );
#print Dumper $content->{'results'}[0];

if ($mode eq 'size') {
    my $numusers=0;
    foreach my $u (@{$content->{'results'}}) {
        # Loop over users
        my $type=$u->{'accountType'};
        next if ($type eq 'app');
        $numusers++;
    }
    $perfLabel='users';
    $perfValue=$numusers;
    $info=sprintf("Group %s has %d users", $groupname, $numusers);
    if ($numusers >= $warn) {
        $status='WARNING';
    }
    if ($numusers >= $crit) {
        $status='CRITICAL';
    }

} else {
    $status="UNKNOWN";
    $info="Unknown plugin mode selected";
}


#############  End of your plugin logic  ##############

# The Screen output should always begin with the readable status value
# ('OK', 'WARNING', 'CRITICAL' or 'UNKNOWN')
my $outstring="$status: $info";

if(defined($perfValue)) {
    my $perfWarnCrit;
    # Compile the performance data. If threshold ranges are in use, format
    # the thresholds in perfdata range format as well.
    if(defined($critLow)) {
        $perfWarnCrit=sprintf("%d:%d;%d:%d", $warnLow, $warn, $critLow, $crit);
    } else {
        $perfWarnCrit=sprintf("%d;%d", $warn, $crit);
    }
    $perfData=sprintf("|%s=%d%s;%s", $perfLabel, $perfValue, $perfUnit, $perfWarnCrit);
}

if(defined($perfValue)) {
    # Concatenate the Screen Ouput and perfdata to stdout so that Nagios can grab it.
    print "$outstring$perfData\n";
} else {
    print "$outstring\n";
}

# Exit with the status exit code appropriate to the textual status.
exit $ERRORS{$status};
