#!/usr/bin/perl -w
# nagios: -epn
#
# Nagios plugin to check sensor data on a Sensaphone IMS-4000
#
# Copyright 2015 Joshua Malone <jmalone@nrao.edu>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

use Net::SNMP;
use Getopt::Long qw(:config no_ignore_case);
use lib qw ( . /usr/lib/nagios/libexec /usr/lib/nagios/plugins );
use utils qw(%ERRORS);

$PROGNAME="check_ims_sensor";
$VERSION=11;

sub print_help () {
    my $help = << "EOH";
Usage: $PROGNAME -H <host address> [-C <community>] [-n <node>] -I <input> [(other options)]

    -I		Input channel number to check
    -n		Node number (Can specify 0 or omit for sensors on host)
    -C		SNMP community string (read is sufficient)
    -w		Warning threshold (supports Nagios range syntax)
    -c		Critical threshold (supports Nagios range syntax)
    -s		Force output to temperature system (F or C)
    -v		Verbose/debugging output
    -u		Override value unit string
    -t		Override input type string

    --list-sensors	List available sensors on selected node
    --list-nodes	List connected nodes

EOH
    print ($help);
    exit $ERRORS{'UNKNOWN'};
}

sub isNodeActive ($) {
    $nodeNumber=shift @_;
    if ($nodeNumber == 0) {
	# Invalid node - this is the host
	return 1;
    }

    my $nodeInUseObj="$ims4000.$nodeNumber.$suf_nodeActive";
    $res = $s->get_request( -varbindlist => [ $nodeInUseObj ] );
    if(!defined($res)) {
	printf("Error retrieving node data: %s\n", $s->error);
    }
    if ($res->{$nodeInUseObj} == 2 ) { 
	return 1;
    } else {
	return 0;
    }
}

### Set some defaults
# Usual default read-only community string
$community="public";
# IMS4000 MIB prefix
$ims4000=".1.3.6.1.4.1.8338.1.1.1";
# For verifying SNMP connectivity
$OIDuptime='.1.3.6.1.2.1.1.3.0';

# OID suffix for node name
$suf_nodeName='10.2.0';
$suf_nodeActive='10.10.0';

# The types of input sensors available
%InputTypes = (
    1=> "temp",		2=> "temp",		3=> "humidity",
    4=> "water",	5=> "extPower",
    6=> "N.C. contact",		7=> "N.O. contact",
    8=> "smoke",	9=> "motion",		10=> "humidity",
    11=> "temp",	12=> "temp", 		16=> "Not Connected",
    17=> "hostPower",	18=> "nodePower",	19=> "battery",
    20=> "sound",	21=> "ip",
);
# SNMP timeout, in seconds
$timeout=5;

# Default to node 1, meaning the host itself
$OIDnode=1;

### Read command line options and override defaults if passed
GetOptions(
    "H|host=s"		=> \$ims,
    "h|help"		=> \$helpme,
    "n|node=i"		=> \$node,
    "I|input=s"		=> \$input,
    "C|community=s"	=> \$community,
    "w|warning=s"	=> \$warn,
    "c|critical=s"	=> \$crit,
    "v|verbose"		=> \$debug,
    "u|unit=s"		=> \$unit,
    "s|system=s"	=> \$system,
    "t|type=s"		=> \$type,
    "V|version"		=> \$doVersion,
    "list-sensors"	=> \$doList,
    "list-nodes"	=> \$doNodes,
) or print_help();

if (!$ims || $helpme) {
    print_help();
}
if ($doVersion) {
    printf("%s by Josh Malone (jmalone at nrao.edu) version %d\n", $PROGNAME, $VERSION);
    exit $ERRORS{'UNKNOWN'};
}
if (defined($warnLow) || defined($critLow)) {
    if (!defined($warnLow) or !defined($critLow)) {
        printf("Error: When using low thresholds, both warning and critical must be supplied!\n");
	exit $ERRORS{'UNKNOWN'};
    }
}

($s, $error) = Net::SNMP->session(
	-hostname => $ims, -community => $community, -timeout => $timeout,
	-version => 1
    ) or die ("Unable to create new SNMP session");
if (!$s) {
    printf("Session error: %s\n", $error);
    exit $ERRORS{'UNKNOWN'};
}

### Check that the host is responding to SNMP
$res = $s->get_request( -varbindlist => [$OIDuptime] );
if(!defined($res)) {
    printf("Unable to query host via SNMP:\n%s\nCheck that SNMP is enabled on the host.\n",
	$s->error);
    exit $ERRORS{'CRITICAL'};
}

### Figure out the OID offset for the chosen node
if ($node) {
    $OIDnode+=$node;
}

### List available nodes that the host knows about
if($doNodes) {
    printf("Available nodes:\n");
    for ($i=1; $i<33; $i++) {
	# Up to 31 nodes are supported, numbered 2 to 32 (1 is host)
	printf("Querying node %d\n", $i) if ($debug);
	my $nodeNameObj="$ims4000.$i.$suf_nodeName";
	my $nodeInUseObj="$ims4000.$i.$suf_nodeActive";
	$res = $s->get_request( -varbindlist => [ $nodeNameObj, $nodeInUseObj ] );
	if(!defined($res)) {
	    printf("Error retrieving node name: %s\n", $s->error);
	}
	if ($res->{$nodeInUseObj} == 2 ) { 
	    printf("Node %d, name %s\n", $i-1, $res->{$nodeNameObj} );
	}
    }
    exit $ERRORS{'UNKNOWN'};
}

# Check to see if node is active before any more activity
$nodeActive=isNodeActive($node);
if (!$nodeActive) {
    printf("CRITICAL: Node %d is not active on this host!\n", $node);
    exit $ERRORS{'CRITICAL'};
}

### List available sensors if requested
if($doList) {
    printf("Available sensors:\n");
    for ($i=1; $i<12; $i++) {
	my $listType="$ims4000.$OIDnode.8.1.1.3.$i";
	my $listLabel="$ims4000.$OIDnode.8.1.1.2.$i";
	my $highLimOID="$ims4000.$OIDnode.8.1.1.14.$i";
	my $lowLimOID="$ims4000.$OIDnode.8.1.1.13.$i";
	printf("Sensor type OID is %s\n", $listType) if ($debug && $i==1);
	$res = $s->get_request(
	    -varbindlist => [ $listType, $listLabel, $highLimOID, $lowLimOID  ],
	);
	if(!defined($res)) {
	    printf("Error retrieving sensor data:\n%s\nAre you querying the IMS *host*?\n",
	    	$s->error);
	    exit $ERRORS{'UNKNOWN'};
	}
	my $type=$res->{$listType};
	if($type==16) {
	    printf("  Ch %d: Not connected\n", $i);
	} else {
	    my $imsLowAlarm=$res->{$lowLimOID};
	    my $imsHighAlarm=$res->{$highLimOID};
	    if ($debug) {
		printf("  Ch %d: Type %s (%d), Name: %s, Threshold: %d:%d\n", $i,
		    $InputTypes{$res->{$listType}}, $res->{$listType}, $res->{$listLabel}, $imsLowAlarm, $imsHighAlarm );
	    } else {
		printf("  Ch %d: Type %s, Name: %s, Threshold: %d:%d\n", $i,
		    $InputTypes{$res->{$listType}}, $res->{$listLabel}, $imsLowAlarm, $imsHighAlarm );
	    }
	}
    }
    printf("\n");
    exit $ERRORS{'UNKNOWN'};
}
if(!$input) { print_help(); }

### Define OIDs for the rest of the interesting values
$typeOID="$ims4000.$OIDnode.8.1.1.3.$input";
$valueOID="$ims4000.$OIDnode.8.1.1.7.$input";
$labelOID="$ims4000.$OIDnode.8.1.1.2.$input";
$highLimOID="$ims4000.$OIDnode.8.1.1.14.$input";
$lowLimOID="$ims4000.$OIDnode.8.1.1.13.$input";
printf("Sensor value OID is %s\n", $valueOID) if ($debug);

### Query the IMS for the sensor type and current value
$res = $s->get_request(
    -varbindlist => [$typeOID, $valueOID, $labelOID, $highLimOID, $lowLimOID ],
);
if(!$res) {
    printf("CRITICAL: SNMP error: %s\n", $s->error);
    exit $ERRORS{'CRITICAL'};
}
$inputValue=$res->{$valueOID};
$inType=$res->{$typeOID};
$inLabel=$res->{$labelOID};
$imsLowAlarm=$res->{$lowLimOID};
$imsHighAlarm=$res->{$highLimOID};
if(!$inLabel eq "" and !$type) {
    $type=$inLabel;
}
if ($debug) {
    printf("Sensor type is %d\n", $inType);
    printf("Sensor label is %s\n", $inLabel);
    printf("Raw value is %s\n", $inputValue);
    printf("IMS config thresholds: %d:%d\n", $imsLowAlarm, $imsHighAlarm);
}

# Use alarm range configured in IMS if no thresholds supplied in arguments
if(!defined($crit)) {
    printf("Using IMS-configured critical thresholds\n") if ($debug);
    $crit=$imsHighAlarm;
    $critLow=$imsLowAlarm;
}

# Adapt to the sensor type
if ($inType==1 or $inType==11) {
    # Temperature in F
    $unit='degrees F' unless ($unit);
    $type="Temperature" unless ($type);
    $perfLabel="temp";
    $perfUnit="F";
    $warn //= 80;
    $crit //= 90;
} elsif($inType==2 or $inType==12) {
    # Temperature in C
    $unit='degrees C' unless ($unit);
    $type="Temperature" unless ($type);
    $perfLabel="temp";
    $perfUnit="C";
    $warn //= 27;
    $crit //= 33;
} elsif($inType==3 or $inType==10) {
    # Humidity (relative %)
    $unit='%' unless ($unit);
    $type="Humidity" unless ($type);
    $perfLabel="humidity";
    $perfUnit="%";
} elsif($inType==17 or $inType==18) {
    # Power - internal; 0 is normal, 1 is power out
    $warn=$crit=1;
    $type='Power fail' unless ($type);
    $perfLabel='powerfail';
} elsif($inType==20) {
    # Sound - usually via internal mic
    $unit='dB' unless ($unit);
    $type='Sound volume' unless ($type);
    $perfLabel='sound';
    $perfUnit=$unit;
    # Default thresholds, in dB
    $warn //= 85;  # unsafe after 8 hrs w/o hearing protection
    $crit //= 94;  # unsafe after 1 hr w/o hearing protection
} elsif($inType==4) {
    # Water sensor
    $warn=$crit=1;
    $type=$inLabel unless ($type);
    $perfLabel='sensor';
} elsif($inType==7) {
    # Normally-open contact
    $warn=$crit=1;
    $type="Dry contact $inLabel";
    $perfLabel='contact';
    $perfUnit='';
} elsif($inType==16) {
    printf("Error: Input %d is not connected\n", $input);
    exit $ERRORS{'UNKNOWN'};
} else {
    printf("Error: Input type %s is unsupported at this time.\n", $InputTypes{$inType} );
    exit $ERRORS{'UNKNOWN'};
}

### Convert temps to desired temperature system
if ($system && ($unit =~ /degrees/) ) {
    if ($perfUnit ne $system) {
    	use Math::Round;
        print("Converting temperature system ") if ($debug);
        if ($system eq 'F') {
            # Convert to F
            printf("to Farenheit\n") if ($debug);
            $inputValue=round($inputValue * 9 / 5 + 32);
            $perfUnit='F';
	    $unit='degrees F';
        } elsif ($system eq 'C') {
            # Convert to C
            printf("to Celsius\n") if ($debug);
            $inputValue=round( ($inputValue-32) * 5 / 9 );
            $perfUnit='C';
	    $unit='degrees C';
        } else {
            # No other systems supported
            printf("Error - invalid temperature system specified!\n");
            exit $ERRORS{'UNKNOWN'};
        }
    }
}

### Process the value
$status="OK";
$warnLow=0;
$critLow=0;
@Warn=split(':', $warn) if (defined($warn));
@Crit=split(':', $crit) if (defined($crit));
if(scalar(@Warn) > 1) {
    printf("Checking low and high warning thresholds\n") if ($debug);
    ($warnLow, $warn)=@Warn;
}
if(scalar(@Crit) > 1) {
    printf("Checking low and high critical thresholds\n") if ($debug);
    ($critLow, $crit)=@Crit;
}
printf("Thresholds in use: W->%d:%d , C->%d:%d\n", $warnLow, $warn, $critLow, $crit) if ($debug);
if($warnLow) {
    # Process lower warning/critical thresholds
    if ($inputValue <= $warnLow) {
        $status="WARNING";
    }
}
if($critLow) {
    if ($inputValue <= $critLow) {
        $status="CRITICAL";
    }
}

if($status eq "OK") {
    # Value is not too low, so check the upper thresholds
    if ($warn and $inputValue >= $warn) {
	$status="WARNING";
    }
    if ($inputValue >= $crit) {
	$status="CRITICAL";
    }
}

$outstring="$status: ";
if ($type) {
    $outstring.="$type is ";
}
$outstring.="$inputValue";
if ($unit) {
    $outstring.=" $unit";
}
if(defined($critLow)) {
    $perfWarnCrit=sprintf("%d:%d;%d:%d", $warnLow, $warn, $critLow, $crit);
} else {
    $perfWarnCrit=sprintf("%d;%d", $warn, $crit);
}
$perfData=sprintf("|%s=%d%s;%s", $perfLabel, $inputValue, $perfUnit, $perfWarnCrit);
print "$outstring$perfData\n";

exit $ERRORS{$status};
